backend:
  name: git-gateway
  repo: tjaynl/rosita.nl
  branch: master # Branch to update (optional; defaults to master)

media_folder: static # Media files will be stored in the repo under images/uploads

collections:
  - label: "Pages"
    name: "pages"
    files:
      - label: "About Page"
        name: "about"
        file: "_src/_includes/content/about.md"
        fields:
          - { label: "Body", name: "body", widget: "markdown" }

  - label: "Events" # Used in the UI
    name: "event" # Used in routes, e.g., /admin/collections/event
    folder: "_src/events" # The path to the folder where the documents are stored
    create: true # Allow users to create new documents in this collection
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}" # Filename template, e.g., YYYY-MM-DD-title.md
    fields: # The fields for each document, usually in front matter
      - { label: "Layout", name: "layout", widget: "hidden", default: "layouts/event.njk" }
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Event Date", name: "date", widget: "datetime" }
      - { label: "Event Image", name: "thumbnail", widget: "image" }
      - { label: "Body", name: "body", widget: "markdown" }

  - label: "Blog" # Used in the UI
    name: "blog" # Used in routes, e.g., /admin/collections/blog
    folder: "src/posts" # The path to the folder where the documents are stored
    create: true # Allow users to create new documents in this collection
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}" # Filename template, e.g., YYYY-MM-DD-title.md
    fields: # The fields for each document, usually in front matter
      - { label: "Layout", name: "layout", widget: "hidden", default: "layouts/blog-post.njk" }
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Post Date", name: "date", widget: "datetime" }
      - { label: "Featured Image", name: "thumbnail", widget: "image" }
      - { label: "Body", name: "body", widget: "markdown" }