backend:
  name: git-gateway
  branch: main
  # repo: tjaynl/rosita.nl
  commit_messages:
    create: Create {{collection}} “{{slug}}”
    update: Update {{collection}} “{{slug}}”
    delete: Delete {{collection}} “{{slug}}”
    uploadMedia: Upload “{{path}}”
    deleteMedia: Delete “{{path}}”

publish_mode: editorial_workflow

media_folder: "_src/static/img/"
public_folder: "/img"

collections:
  - name: "settings"
    label: "Settings"
    delete: false # Prevent users from deleting documents in this collection
    editor:
      preview: false
    files:
      - name: "general"
        label: "Site Settings"
        file: "_src/_data/site.yml"
        description: "General Site Settings"
        fields:
          - { label: "Global title", name: "title", widget: "string" }
          - { label: "Global description", name: "description", widget: "text" }
          - { label: "Stream Source", name: "audio_source", widget: "string"}
          - { label: "Logo", name: "logo", widget: "image", default: "/static/img/logo.svg" }
          - label: "Post Settings"
            name: posts
            widget: "object"
            fields:
              - {
                  label: "Number of posts on frontpage",
                  name: front_limit,
                  widget: number,
                  min: 1,
                  max: 10,
                }

  - label: "Pages"
    name: "pages"
    files:
      - label: "Landing Page"
        name: "landing"
        file: "_src/index.yml"
        fields:
          - label: "Hero"
            name: "hero"
            widget: "object"
            fields:
              - { label: "Title", name: "title", widget: "string" }
              - { label: "Intro", name: "intro", widget: "text" }
          - label: "About"
            name: "about"
            widget: "object"
            fields:
              - { label: "Title", name: "title", widget: "string" }
              - { label: "Intro", name: "intro", widget: "markdown" }
              - { label: "Image", name: "image", widget: "image" }

      - label: "About Page"
        name: "about"
        file: "_src/content/pages/about.md"
        fields:
          - { label: "Title", name: "title", widget: "string" }
          - { label: "Description", name: "description", widget: "text" }
          - { label: "Body", name: "body", widget: "markdown" }

  - label: "Blog" #  Used in the UI
    name: "blog" # Used in routes, e.g., /admin/collections/blog
    folder: "_src/blog/" # The path to the folder where the documents are stored
    public_folder: "/static/img/blog"
    description: "Create or edit blog posts"
    create: true # Allow users to create new documents in this collection
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}" # Filename template, e.g., YYYY-MM-DD-title.md
    fields: # The fields each document in this collection have
      - { label: "Title", name: "title", widget: "string", tagname: "h1" }
      - { label: "Draft", name: "draft", widget: "boolean", default: false }
      - {
          label: "Publish Date",
          name: "date",
          widget: "datetime",
          date_format: "DD.MM.YYYY",
          time_format: "HH:mm",
          format: "DD-MM-YYYY HH:mm",
        }
      - label: "Cover Image"
        name: "cover_image"
        widget: "image"
        required: false
        tagname: ""
      - label: "Tags"
        name: "tags"
        widget: "list"
        summary: "{{fields.name}}"
        fields: 
          - { label: "Name", name: "name", widget: "string" }
      - { label: "Categorie", name: "categorie", widget: "string" }
      - { label: "Body", name: "body", widget: "markdown", hint: "Main content goes here." }