backend:
  name: git-gateway
  repo: tjaynl/rosita.nl
  branch: master # Branch to update (optional; defaults to master)

media_folder: "static/img/uploads" # Media files will be stored in the repo under images/uploads
public_folder: "/img/uploads"

collections:
  - label: "Pages"
    name: "pages"
    files:
      - label: "Home Page"
        name: "frontpage"
        file: "_src/index.yml"
        fields:
          - { label: "Hero Title", name: "header.title", widget: "string" }
          - { label: "Hero intro", name: "header.intro", widget: "markdown" }
          - { label: "About Title", name: "about.title", widget: "string" }
          - { label: "About intro", name: "about.description", widget: "markdown" }
          - { label: "About image", name: "about.image", widget: "image" }
      - label: "About Page"
        name: "about"
        file: "_src/about.md"
        fields:
          - { label: "Layout", name: "layout", widget: "hidden", default: "layouts/base.njk" }
          - { label: "Title", name: "title", widget: "string" }
          - { label: "Body", name: "content", widget: "markdown" }

  - label: "Events" # Used in the UI
    name: "event" # Used in routes, e.g., /admin/collections/event
    folder: "_src/events/" # The path to the folder where the documents are stored
    description: "Create or edit events"
    create: true # Allow users to create new documents in this collection
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}" # Filename template, e.g., YYYY-MM-DD-title.md
    fields: # The fields for each document, usually in front matter
      - { label: "Layout", name: "layout", widget: "hidden", default: "layouts/event.njk" }
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Event Date", name: "date", widget: "datetime" }
      - { label: "Event Image", name: "thumbnail", widget: "image" }
      - { label: "Body", name: "body", widget: "markdown" }

  - label: "Blog" # Used in the UI
    name: "blog" # Used in routes, e.g., /admin/collections/blog
    folder: "_src/blog/" # The path to the folder where the documents are stored
    description: "Create or edit blog posts"
    create: true # Allow users to create new documents in this collection
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}" # Filename template, e.g., YYYY-MM-DD-title.md
    fields: # The fields for each document, usually in front matter
      - { label: "Layout", name: "layout", widget: "hidden", default: "layouts/blog-post.njk" }
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Post Date", name: "date", widget: "datetime" }
      - { label: "Featured Image", name: "thumbnail", widget: "image" }
      - { label: "Body", name: "body", widget: "markdown" }