title: Rosita.nl
description: De radio van Twente en omstreken
logo: /assets/images/logo.svg
email: info@rosita.nl
netlify_site_id: b5a3ba91-01c0-46e8-8fb2-4eaf8fd77f0f
audio_source: https://ex52.voordeligstreamen.nl/8004/stream
post:
  front_limit: 3
